Sprint 3
Alegiter/middle.messenger.praktikum.yandex pull request #3
Opened 2021-09-01 18:59 UTC by Alegiter

Есть нерешённые вопросы, помогите разобраться. Подробности в chat-socket.ts и ещё вопрос в chat.api.ts

2021-09-02 20:10 UTC, bhoodream requested changes
Интересная работа, интересные решения! Нашел несколько моментов по коду за которые смог зацепиться, а также выписал проблемы с которыми столкнулся при использовании проекта. Работу нужно доделывать:

- [ ] не подгружаются/отправляются сообщения (как я понял функционал просто не реализован, в силу проблем с сокетом)
- [ ] после установки зависимостей файл `package-lock.json` изменен... Почему то в репозитории не актуальный лок файл
- [ ] при обновлении данных пользователя, происходит редирект в настройки, где отображаются устаревшие данные. После рефреша данные отображаются корректные
- [ ] при редактировании аватара не дает выбрать `jpeg` файлы, странно... ведь это изображения
- [ ] при рефреше страницы в настройках перекидывает в чат, что странно
- [ ] не добавляются/удаляются пользователи, происходит 500 ошибка на сервере (чинится фиксом запроса юзеров чата)
- [ ] ошибки по eslint ✖ 36 problems (3 errors, 33 warnings)
- [ ] ошибки по stylelint
- [ ] команда test падает с ошибкой @parcel/core: Failed to resolve '../../../components/component.spec' from './test/tests.spec.ts' (жаль, интересно было посмотреть тесты)
- [ ] в нетлифай все урлы кроме рута 404, также апи ходит не туда (прокся там естественно не работает)

2021-09-02 20:10 UTC, bhoodream commented on src/core/api/services/auth.api.ts
> +        return this.http.get('/user').then((xhr) => {
Вот эти вот свитчи выглядят как неприятное дублирование кода. Возможно, если порефачить `http.request` можно от этого избавиться!

2021-09-02 20:10 UTC, bhoodream commented on src/core/api/services/chats.api.ts
> +     * Может быть где-то неправильно строю запрос, глаза уже замылились
Это должен быть `GET` запрос, а у тебя `POST` :) И правда глаза малость замылились ;)

2021-09-02 20:10 UTC, bhoodream commented on src/core/api/types/sign-up-request.ts
> +    first_name: 'string';
Ты здесь вместо того чтобы указать тип `string`, ничайно указал строковые примитивные значения `'string'`.

2021-09-02 20:10 UTC, bhoodream commented on src/core/api/web-socket/chat-socket.ts
> + * Помогите разобраться, уже пару дней не двигаемся с этого места
Попробуй убрать прокси до апи (достаточно удалить `.proxyrc.json` и перезапустить сервер) и пропиши нормальный апи урл в константах `https://ya-praktikum.tech/api/v2`. И сокет магическим образом перестанет обрываться и все заработает! 

А почему... это тебе домашнее задание: определить почему прокся ломала генерацию токена. Ммм, какой увлекательный дебаг-квест тебя ждет, обзавидуешься! :D

2021-09-02 20:10 UTC, bhoodream commented on src/core/storage/storage.ts
> +const test = new Storage();
Такое хорошо бы подчищать, не надо засорять кодовую базу.

2021-09-02 20:10 UTC, bhoodream commented on src/pages/chats/chats.ts
> +                        this.controller.getChatToken(chat.id).then((token) => {
Наблюдается неверное использование промисов, их необходимо выстраивать в одну цепочку, типа:
```
Promise(...)
  .then((data) => useData(data))
  .then((newData) => ...)
  .then(...)
  .catch(...)
``` 

Вкладывая промис в промис ты скатываешься во всеми ненавистный колбэк хэл все больше и больше увеличивая вложенность и снижая читабельность кода.

2021-09-02 20:10 UTC, bhoodream commented on src/pages/chats/chats.ts
> +            // const test = [];
Закомментированный код является мусором и должен быть безжалостно удален. Если тебе вдруг понадобится этот код, ты сможешь найти его в прошлых версиях файла.

2021-09-04 21:13 UTC, Alegiter commented
Я сделал по минимуму, т.к. крайне сильно растянул третий спринт(

2021-09-06 05:45 UTC, bhoodream approved these changes
Раз у тебя так растянулся третий спринт, то не вижу смысла тебя задерживать! Практически все проблемы, о которых я говорил - исправлены, что очень хорошо. Поэтому от меня АПРУВ и удачи тебе дальше!

2021-09-08 09:28 UTC, merged